USE [VOICE_CONTROLLED_PARKINGFACILITY];
GO

CREATE OR ALTER FUNCTION func_LeesWerkwoord
(
	@zin VARCHAR(100)
)

RETURNS VARCHAR(30)
AS
BEGIN
	DECLARE @WerkwoordResult VARCHAR(30) = (
		SELECT value  
		FROM STRING_SPLIT(@zin, ' ')
		ORDER BY (SELECT NULL)
		OFFSET 1 ROW
		FETCH NEXT 1 ROW ONLY
		)

	RETURN @WerkwoordResult
END