USE [VOICE_CONTROLLED_PARKINGFACILITY]


IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TRANSACTIE_GESCHIEDENIS')
begin
	ALTER TABLE [TRANSACTIE_GESCHIEDENIS] DROP CONSTRAINT FK_TransactieBestuurder;
	ALTER TABLE [TRANSACTIE_GESCHIEDENIS] DROP CONSTRAINT FK_TransactieKenteken;
	DROP TABLE [TRANSACTIE_GESCHIEDENIS];
end

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'PARKEERLOCATIE')
begin
	ALTER TABLE [PARKEERLOCATIE] DROP CONSTRAINT FK_LocatieKenteken;
	DROP TABLE [PARKEERLOCATIE];
end

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'AUTO')
begin
	ALTER TABLE [AUTO] DROP CONSTRAINT FK_AutoBestuurder;
	DROP TABLE [AUTO];
	DROP TABLE IF EXISTS [BESTUURDER];
end

CREATE TABLE [BESTUURDER] (
	Naam VARCHAR(10) PRIMARY KEY
)

CREATE TABLE [AUTO] (
	Kenteken VARCHAR(10) PRIMARY KEY,
	FK_Naam VARCHAR(10),
	CONSTRAINT FK_AutoBestuurder FOREIGN KEY (FK_Naam) REFERENCES [BESTUURDER](Naam)
)

CREATE TABLE [PARKEERLOCATIE] (
	ParkeerSpot VARCHAR(10) PRIMARY KEY,
	Bezet BIT, -- Is de parkeerspot bezet? (Y/N)
	FK_Kenteken VARCHAR(10),
	CONSTRAINT FK_LocatieKenteken FOREIGN KEY (FK_Kenteken) REFERENCES [AUTO](Kenteken)
)

CREATE TABLE [TRANSACTIE_GESCHIEDENIS] (
	ID INT PRIMARY KEY,
	FK_Naam VARCHAR(10),
	CONSTRAINT FK_TransactieBestuurder FOREIGN KEY (FK_Naam) REFERENCES [BESTUURDER](Naam),
	FK_Kenteken VARCHAR(10),
	CONSTRAINT FK_TransactieKenteken FOREIGN KEY (FK_Kenteken) REFERENCES [AUTO](Kenteken),
	CheckIn DATETIME,
	CheckOut DATETIME,
	Facturering DECIMAL(9,2)
)