USE [VOICE_CONTROLLED_PARKINGFACILITY]


DROP TABLE IF EXISTS[ZWAKKEWW];
DROP TABLE IF EXISTS[STERKEWW];

CREATE TABLE STERKEWW(
	Infinitief VARCHAR(30)
,	Stam VARCHAR(30)
,	tt2ep VARCHAR(30)
,	vd VARCHAR(30)
,	vt VARCHAR(30)
,	hulpwerkwoord VARCHAR(10)
,	Actie VARCHAR(30)
);

CREATE TABLE ZWAKKEWW(
	Infinitief VARCHAR(30)
,	Stam VARCHAR(30)
,	hulpwerkwoord VARCHAR(10)
,	Actie VARCHAR(30)
);