USE [VOICE_CONTROLLED_PARKINGFACILITY];
GO

CREATE OR ALTER FUNCTION func_LeesKenteken
(
	@zin VARCHAR(100)
)

RETURNS VARCHAR(10)
AS
BEGIN
	DECLARE @KentekenResult VARCHAR(10) = (
		SELECT RIGHT(@zin, CHARINDEX(' ', REVERSE(@zin)) - 1)
		);

	RETURN @KentekenResult
END