USE [TAAL]
GO 

CREATE OR ALTER FUNCTION FUNC_ActieBepaler
(
	@Stam VARCHAR(10)
)

RETURNS VARCHAR(50)
AS
BEGIN
	DECLARE @Actie VARCHAR(50)

	IF EXISTS (SELECT * FROM ZWAKKE_WW WHERE Stam = @Stam)
		BEGIN
			SELECT @Actie = Actie FROM ZWAKKE_WW WHERE Stam = @Stam
		END

	RETURN @Actie
END